{
 "title": "技術書店用ダッシュボード",
 "description": "技術書店の机の上で見せる用のダッシュボード",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Chef Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"chef-service\"}"
    }
   ]
  },
  {
   "title": "Waiter Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"waiter-service\"}"
    }
   ]
  },
  {
   "title": "BB Productions",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"bb-productions\"}"
    }
   ]
  },
  {
   "title": "リクエストトータル",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "http_requests_total{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "当たりの時間",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "http_requests_total{path=\"/karubikuppa\"} % 10 == bool 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "クジの結果",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 18 },
   "targets": [
    {
     "expr": "http_requests_total{path=\"/karubikuppa\"} % 10",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}