apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true
    jsonData:
      timeInterval: 15s
      exemplarTraceIdDestinations:
      - name: trace_id
        datasourceUid: Tempo
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      derivedFields:
      - datasourceUid: Tempo
        matcherRegex: '"trace_id":"(\w+)"'
        name: trace_id
        url: '$${__value.raw}'
        urlDisplayLabel: 'Tempo'
    secureJsonData:
      httpHeaderValue1: "tenant1"
  - name: Tempo
    type: tempo
    url: http://tempo:3200
    jsonData:
      lokiSearch:
        datasourceUid: 'Loki'
      tracesToLogs:
        datasourceUid: 'Loki'
        mappedTags: [{ key: 'service.name', value: 'container' }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
